package com.mecklon.order.models.types;

public enum SagaEventHistoryStatus {
    PRODUCT_RESERVED_EVENT,
    CREATED_PAYMENT_EVENT,
    FAILED_PRODUCT_RESERVED_EVENT,
    FAILED_CREATE_ORDER_ID_EVENT,
    RELEASED_PRODUCT_EVENT,
    EXPIRED_PAYMENT_EVENT,
    REFUNDED_EVENT,
    REFUND_FAILED_EVENT,
    CREATE_PAYMENT_COMMAND,
    RELEASE_PRODUCT_ORDER_ID_CREATION_FAILED_COMMAND,
    RELEASE_PRODUCT_PAYMENT_EXPIRED_COMMAND,
    RESERVE_PRODUCT_COMMAND,
    PAYMENT_SUCCESSFUL_EVENT,
    CREATED


}
