spring.application.name=order
server.port=9092
spring.data.mongodb.uri=mongodb+srv://fernandesmecklon3_db_user:6f7gk4p5ACS3odnv@cluster0.kpmcduk.mongodb.net/order?appName=Cluster0


spring.kafka.producer.bootstrap-servers=localhost:9096
spring.kafka.bootstrap-servers=localhost:9096
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.mecklon.core.*

reserve-product-command=reserve.product.command
reserved-product-event=reserved.product.event
create-payment-command=create.payment.event
created-payment-event=created.payment.event
failed-reserved-product-event=failed.reserved.product.event
failed-created-payment-event=failed.created.payment.event
release-product-command=release.product.command
released-product-event=released.product.event
successful-payment-event=successful.payment.event
expired-payment-event=expired.payment.event
payment-refund-status-update=payment.refund.status.update

spring.kafka.consumer.group-id=order-service-${random.value}-

spring.kafka.producer.acks=all
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.producer.properties.enable.max.in.flight.request.per.connection=5

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.data.redis.listener=DEBUG

razorpay.webhook.secret=my-super-secret-webhook-key
razorpay.key-id=rzp_test_TBqihEjifdnMkP
razorpay.key-secret=BihXICcz7g3M0EDs2Oy8ac6Q