spring.application.name=payment
server.port=9093
spring.data.mongodb.uri=mongodb+srv://fernandesmecklon3_db_user:6f7gk4p5ACS3odnv@cluster0.kpmcduk.mongodb.net/payment?appName=Cluster0

spring.kafka.producer.bootstrap-servers=localhost:9096
spring.kafka.bootstrap-servers=localhost:9096
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.mecklon.core.*

reserve-product-command=reserve.product.command
reserved-product-event=reserved.product.event
create-payment-command=create.payment.event
created-payment-event=created.payment.event
failed-created-payment-event=failed.created.payment.event
successful-payment-event=successful.payment.event
expired-payment-event=expired.payment.event
payment-refund-status-update=payment.refund.status.update

spring.kafka.consumer.group-id=payment-service-${random.value}-

spring.kafka.producer.acks=all
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.producer.properties.enable.max.in.flight.request.per.connection=5




# Circuit Breaker

resilience4j.circuitbreaker.instances.testCircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.testCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.testCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.testCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.testCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.testCircuitBreaker.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.testCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.testCircuitBreaker.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.testCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true

# Retry

resilience4j.retry.instances.testRetry.max-attempts=4
resilience4j.retry.instances.testRetry.wait-duration=10s
resilience4j.retry.instances.testRetry.enable-exponential-backoff=true
resilience4j.retry.instances.testRetry.exponential-backoff-multiplier=2

# Time Limiter


resilience4j.timelimiter.instances.testTimeLimiter.timeout-duration=10s
resilience4j.timelimiter.instances.testTimeLimiter.cancel-running-future=true

# Actuator

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

razorpay.webhook.secret=my-super-secret-webhook-key
razorpay.key-id=rzp_test_TBqihEjifdnMkP
razorpay.key-secret=BihXICcz7g3M0EDs2Oy8ac6Q